language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
#install: 
#  - mvn -N io.takari:maven:wrapper
#before_script:
#  - chmod +x mvnw
script: >-
  mvn --global-settings ./.travis/settings.xml -DforceContextQualifier=$TRAVIS_BUILD_NUMBER
  && mvn --global-settings ./.travis/settings.xml -DbuildBy="Travis CI - $TRAVIS_BUILD_WEB_URL"
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
  local_dir: "./update-site/target/repository"
  github_token: $GITHUB_TOKEN
  wait-until-deployed: true

