language: java
cache:
  directories:
  - "$HOME/.m2"
#install: 
#  - mvn -N io.takari:maven:wrapper
#before_script:
#  - chmod +x mvnw
script: >-
  maven --global-settings ./.travis/settings.xml -DforceContextQualifier=$TRAVIS_BUILD_NUMBER &&
  maven --global-settings ./.travis/settings.xml deploy

